version: '2'

networks:
  basic:

services:
  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    ports: 
      - 8080:8080
      - 8443:8443
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=$PASS
    volumes:
      - ./keycloak-tmp:/tmp
    networks:
      - basic

  gatekeeper:
    image: keycloak/keycloak-gatekeeper
    container_name: gatekeeper
    ports:
      - 3000:3000
    volumes:
      - ./gatekeeper/config.yml:/etc/keycloak/config.yml
      - ./certs:/etc/keycloak/certs
    entrypoint:
      - /opt/keycloak-gatekeeper
      - --config=/etc/keycloak/config.yml
    networks: 
      - basic

  gatekeeper-02:
    image: keycloak/keycloak-gatekeeper
    container_name: gatekeeper-02
    ports:
      - 3001:3001
    volumes:
      - ./gatekeeper/config-02.yml:/etc/keycloak/config.yml
      - ./certs:/etc/keycloak/certs
    entrypoint:
      - /opt/keycloak-gatekeeper
      - --config=/etc/keycloak/config.yml
    networks: 
      - basic
