#discovery-url: https://$SSO_SERVER_IP:443/auth/realms/demo
discovery-url: http://$SSO_SERVER_IP:8080/auth/realms/demo
client-id: demo-backend-service
client-secret: $CLIENT-SECRET
enable-default-deny: true
secure-cookie: false
#encryption_key: $ENCRYPTION_KEY
listen: :3001
redirection-url: http://$SSO_SERVER_IP:3001
upstream-url: http://$SSO_SERVER_IP:9091
skip-openid-provider-tls-verify: true

#scopes:
#- demo-member
#- demo-admin

resources:
- uri: /demo-frontend-api
  methods:
  - GET
  roles:
  - demo-backend-service:demo-frontend-role

- uri: /external-service-api
  methods:
  - GET
  roles:
  - demo-backend-service:other-external-services-role

headers:
  gateway: http://$SSO_SERVER_IP:3001
