discovery-url: http://$SSO_SERVER_IP:8080/auth/realms/demo
#discovery-url: https://$SSO_SERVER_IP:443/auth/realms/demo
client-id: demo-service
client-secret: $CLIENT_SECRET
enable-default-deny: true
secure-cookie: false
#encryption_key: $ENCRYPTION_KEY
listen: :3000
redirection-url: http://$SSO_SERVER_IP:3000
upstream-url: http://$SSO_SERVER_IP:9090
skip-openid-provider-tls-verify: true

scopes:
- admin-apis
- member-apis

resources:
- uri: /admin
  methods:
  - GET
  roles:
  - admin-api-user

- uri: /member
  methods:
  - GET
  roles:
  - member-api-user

headers:
  gateway: http://$SSO_SERVER_IP:3000
