discovery-url: http://localhost:8080/auth/realms/demo
client-id: vanilla
client-secret: $CLIENT_SECRET
listen: :3000
enable-default-deny: true
enable-refresh-tokens: true
enable-logging: true
enable-json-logging: true
enable-encrypted-token: false
enable-logout-redirect: true
no-redirects: false
secure-cookie: false
forwarding-username: true
forwarding-password: true
tls-cert: /etc/keycloak/cert.crt
tls-private-key: /etc/keycloak/cert.key
redirection-url: http://127.0.0.1:3000
encryption-key: $ENCRYPTION_KEY
upstream-url: http://127.0.0.1:9090
upstream-keepalives: true
skip-upstream-tls-verify: true
skip-openid-provider-tls-verify: true
scopes: []
headers:
  myheader_name: my_header_value
match-claims:
  aud: openvpn
  iss: http://localhost:8080/auth/realms/demo
add-claims:
- testTempName
resources:
- uri: /admin/*
  methods:
  - GET
  roles:
    - vanilla:admin
- uri: /test/*
  white-listed: true
- uri: /admin/*
  methods:
  - GET
  roles:
    - openvpn:vpn-user
    - openvpn:prod-vpn
cors-max-age: 1h
